  joint_state_publisher:
    type: joint_state_controller/JointStateController
    publish_rate: 50.0

# controllers ---------------------------------------
  reaction_wheel_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: reaction_wheel_joint
    pid: {p: 20000.0, i: 800.0, i_clamp: 15000.0, d: 0.0}

  reaction_wheel_position_controller:
    type: effort_controllers/JointPositionController
    joint: reaction_wheel_joint
    pid: {p: 20000.0, i: 0.0, i_clamp: 0.0, d: 0.0}
